
services:
  auth_db:
    env_file:
        - path: ./.env
          required: true
    image: postgres
    build: .
    container_name: auth_db
    restart: always
    ports:
      - "${AUTH_DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${AUTH_DB_USERNAME}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
      POSTGRES_DB: ${AUTH_DB_DATABASE}
    volumes:
      - auth_pgdata:/var/lib/postgresql/auth
      #- ./scripts/:/docker-entrypoint-initdb.d
    networks:
        - default
  
  auth:
    env_file:
      - path: ./.env
        required: true
    container_name: auth
    restart: always
    ports: 
      - "8090:8090"
    build: 
      context: ./authentication/
      dockerfile: ./authentication/Dockerfile 
    depends_on:
      - auth_db
    networks: 
      - default
  messages_db:
    env_file:
        - path: ./.env
          required: true
    image: postgres
    build: .
    container_name: messages_db
    restart: always
    ports:
      - "${MESSAGES_DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${MESSAGES_DB_USERNAME}
      POSTGRES_PASSWORD: ${MESSAGES_DB_PASSWORD}
      POSTGRES_DB: ${MESSAGES_DB_DATABASE}
    volumes:
      - messages_pgdata:/var/lib/postgresql/messages
      #- ./scripts/:/docker-entrypoint-initdb.d
    networks:
        - default

volumes:
  auth_pgdata:
  messages_pgdata:

networks:
  default:
